version: '3.8'

services:
  backend:
    build: .
    container_name: biothings-backend
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - GEMINI_THINKING_BUDGET=${GEMINI_THINKING_BUDGET:-8192}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - biothings-network

  frontend:
    build: ./frontend
    container_name: biothings-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - DOCKER_ENV=true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - biothings-network

  # Optional: Add Redis for production
  # redis:
  #   image: redis:7-alpine
  #   container_name: biothings-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - biothings-network

networks:
  biothings-network:
    driver: bridge