services:
  - type: web
    name: biothings
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: GEMINI_THINKING_BUDGET
        value: 8192
    healthCheckPath: /api/health
    autoDeploy: true