apiVersion: 1

datasources:
  - name: BioThings Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData:
      # Add authentication if needed
      # httpHeaderValue1: 'Bearer your-token-here'

  - name: BioThings Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: biothings-logs-*
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.8.0"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5

  - name: BioThings Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: 'biothings-elasticsearch'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          {
            key: 'service.name',
            value: 'service'
          }
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      nodeGraph:
        enabled: true