global:
  smtp_smarthost: localhost:587
  smtp_from: biothings-alerts@company.com
  resolve_timeout: 5m
route:
  group_by:
  - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: web.hook
  routes:
  - match:
      severity: critical
    receiver: critical-alerts
    repeat_interval: 15m
  - match:
      component: cost
    receiver: cost-alerts
    repeat_interval: 4h
  - match:
      component: security
    receiver: security-alerts
    repeat_interval: 30m
receivers:
- name: web.hook
  webhook_configs:
  - url: http://localhost:5001/webhook
    send_resolved: true
- name: critical-alerts
  email_configs:
  - to: oncall@company.com
    subject: 'CRITICAL: BioThings Alert - {{ .GroupLabels.alertname }}'
    body: '{{ range .Alerts }}{{ .Annotations.summary }}

      {{ .Annotations.description }}

      {{ .Annotations.action_required }}{{ end }}'
  slack_configs:
  - api_url: ${SLACK_WEBHOOK_URL}
    channel: '#biothings-critical'
    title: 'CRITICAL: {{ .GroupLabels.alertname }}'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
- name: cost-alerts
  email_configs:
  - to: finance@company.com
    subject: BioThings Cost Alert - {{ .GroupLabels.alertname }}
    body: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
- name: security-alerts
  email_configs:
  - to: security@company.com
    subject: BioThings Security Alert - {{ .GroupLabels.alertname }}
    body: '{{ range .Alerts }}{{ .Annotations.description }}

      Action: {{ .Annotations.action_required }}{{ end }}'
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - component
